name: leap3d
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - pytorch
  - lightning
  - python-dotenv
  - wandb
  - ipykernel
  - matplotlib
  - openh264
  - scipy
  - conda-build
  - conda-verify
  - pytest
  - h5py
  - torchmetrics
  - typer
